### ISSUE TITLE
Quarry isn't destroying blocks

### ISSUE THREAD

**Issue by Avedoor** [ekul6547/LapisCore-Datapacks#1]
I installed the datapack and everything was working fine, all the crafting recipes and everything. When I crafted the quarry and placed it, it shows the red particle where it should be destroying blocks but it doesn't actually break or drop anything.

**Comment by ekul6547** [comment]
What version are you playing on? It will only work for 1.14
Try doing /forceload add 0 0
Try opening your console (when you launch the game)
Do you get any errors when loading the world / placing the quarry?
The quarry will not work in other dimensions, only the overworld.
