### ISSUE TITLE
version 0.5. batteries aren't crafting 

### ISSUE THREAD

**Issue by Nathan22211** [ekul6547/LapisCore-Datapacks#3]
you didn't change the recipe on us from the looks of it

**Comment by ekul6547** [comment]
The recipe is:
```
#G#
IRI
INI
```
I is iron ingot
N is iron **nugget**
\# must be blank
R is redston **dust**
G is gold **nugget**

They aren't crafted in a crafting table, but in the Lapis Workbench.
The lapis workbench is crafted like so:
```
###
LRL
ISI
```
I = iron bar,  S = smithing table,  L = lapis lazuli,  R = redstone dust

The next update to everything will be updating all of the books.

**Comment by Nathan22211** [comment]
![2019-05-20_16 22 37](https://user-images.githubusercontent.com/35241068/58052958-cfabff80-7b1b-11e9-948e-489776db9f96.png)
proves my point that the crafting for it is broke (I cheated in that battery)
![2019-05-20_16 24 16](https://user-images.githubusercontent.com/35241068/58052979-de92b200-7b1b-11e9-9ed1-16e24ad29319.png)
also found another bug with the datapack, the charger doesn't kill itself when broken or places properly.

i'm in 1.14.2 pre realese 2 so maybe that's why? i'll have to test 1.14.1 to see.

**Comment by ekul6547** [comment]
I'm honestly not sure what's preventing it. Can you try these:

Do you have any other datapacks installed?
Is there any errors in console?

I updated automated quarries to v0.6, that might fix it, and LapisCore is now v0.2
I've been making these in 1.14.2 pre-release 2, but have been re-testing them in 1.14.1, and they all work for me.

Try picking up all of the blocks, then doing /trigger LapisAdminMenu
Then there should be an option to uninstall, and it will remove all scoreboard objective created by LapisCore and automated quarries.
Then do /scoreboard objectives list
What objectives are left over from uninstalling?

Do you have randomTickSpeed increased? I think that has caused a couple of issues in the past, but it should still craft.

Go into the datapack .zip for automated quarries, what do the file at data/quarry/main.mcfunction look like? There should be this line near the top:
`execute as @e[tag=Workbench] if score @s WorkbenchItems matches 0 run function quarry:wbrecipes/_checkrecipes`
And must not have a # in-front of it.
