### ISSUE TITLE
Charger deletes partially and fully charged chargeable items (drill, katana)

### ISSUE THREAD

**Issue by Thaumatarge** [ekul6547/LapisCore-Datapacks#4]
For an unknown reason the charger will delete any chargeable items above a certain amount of charge, apart from batteries. This includes the drill and the katana... Putting in a completely discharged item will charge it properly, however at a certain point the item will disappear.

**Comment by ekul6547** [comment]
Just released v0.8 hotfix 3 that fixes this. Thanks for pointing it out.
