### ISSUE TITLE
The storage servers should be shulker boxes

### ISSUE THREAD

**Issue by A2va** [ekul6547/LapisCore-Datapacks#7]
My idea is to put shulker boxes for the storage servers so that it is movable. The terminal would still be a barrel to be able to load and unload the shuker boxes in the terminal

**Comment by ekul6547** [comment]
While that's not a bad idea, the problem is that there is a lot of technicality for the servers.
It's still a decent idea, I'll look into at some point.
Anyway, any more issues, problems or suggestions, please put them on the discord:
https://discord.gg/rPr2euY
